/**
 * AddGoal Data
 * Goal categories and templates configuration
 */

import {
  Dumbbell,
  Moon,
  Apple,
  Pill,
  Brain,
  Sparkles,
  Footprints,
  Timer,
  Flame,
  Droplets,
  Salad,
  Heart,
  Bike,
  Waves,
  Move,
  Clock,
  Smartphone,
  TreePine,
  Book,
  Sun,
  Beef,
  Cherry,
  Fish,
  Utensils,
  Candy,
  Wheat,
  Wind,
  Sunrise,
  BedDouble,
  Activity,
  Target,
} from 'lucide-react';
import type { GoalCategory } from './types';

export const goalCategories: GoalCategory[] = [
  {
    id: 'exercise',
    name: 'Exercise',
    icon: Dumbbell,
    color: 'text-sky-400',
    bgColor: 'bg-sky-500/10',
    borderColor: 'border-sky-500/30',
    goals: [
      {
        id: 'exercise_minutes',
        name: 'Exercise Minutes',
        icon: Timer,
        unit: 'min',
        defaultTarget: 150,
        minTarget: 30,
        maxTarget: 300,
        step: 15,
        description: 'Total minutes of exercise per week',
      },
      {
        id: 'step_days',
        name: '7K+ Step Days',
        icon: Footprints,
        unit: 'days',
        defaultTarget: 5,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Days hitting 7,000+ steps',
      },
      {
        id: 'workouts',
        name: 'Workouts',
        icon: Flame,
        unit: 'workouts',
        defaultTarget: 3,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Number of workout sessions per week',
      },
      {
        id: 'strength_days',
        name: 'Strength Training Days',
        icon: Dumbbell,
        unit: 'days',
        defaultTarget: 2,
        minTarget: 1,
        maxTarget: 6,
        step: 1,
        description: 'Days with strength/resistance training',
      },
      {
        id: 'cardio_sessions',
        name: 'Cardio Sessions',
        icon: Activity,
        unit: 'sessions',
        defaultTarget: 3,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Cardio workout sessions per week',
      },
      {
        id: 'stretching_days',
        name: 'Stretching/Yoga Days',
        icon: Move,
        unit: 'days',
        defaultTarget: 3,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Days with stretching or yoga',
      },
      {
        id: 'cycling_miles',
        name: 'Cycling Miles',
        icon: Bike,
        unit: 'miles',
        defaultTarget: 20,
        minTarget: 5,
        maxTarget: 100,
        step: 5,
        description: 'Total miles cycled per week',
      },
      {
        id: 'swimming_laps',
        name: 'Swimming Laps',
        icon: Waves,
        unit: 'laps',
        defaultTarget: 20,
        minTarget: 5,
        maxTarget: 100,
        step: 5,
        description: 'Total laps swum per week',
      },
      {
        id: 'active_minutes',
        name: 'Active Minutes',
        icon: Target,
        unit: 'min',
        defaultTarget: 300,
        minTarget: 60,
        maxTarget: 600,
        step: 30,
        description: 'Total active minutes (any movement)',
      },
    ],
  },
  {
    id: 'sleep',
    name: 'Sleep',
    icon: Moon,
    color: 'text-violet-400',
    bgColor: 'bg-violet-500/10',
    borderColor: 'border-violet-500/30',
    goals: [
      {
        id: 'sleep_nights',
        name: '7+ Hour Nights',
        icon: Moon,
        unit: 'nights',
        defaultTarget: 6,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Nights with 7+ hours of sleep',
      },
      {
        id: 'consistent_bedtime',
        name: 'Consistent Bedtime',
        icon: Clock,
        unit: 'nights',
        defaultTarget: 5,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Nights going to bed within 30 min of target',
      },
      {
        id: 'screen_free',
        name: 'Screen-Free Evenings',
        icon: Smartphone,
        unit: 'nights',
        defaultTarget: 4,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'No screens 1 hour before bed',
      },
      {
        id: 'early_nights',
        name: 'Early Nights',
        icon: BedDouble,
        unit: 'nights',
        defaultTarget: 5,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Asleep before midnight',
      },
    ],
  },
  {
    id: 'nutrition',
    name: 'Nutrition',
    icon: Apple,
    color: 'text-emerald-400',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    goals: [
      {
        id: 'veggie_days',
        name: '5+ Veggie Days',
        icon: Salad,
        unit: 'days',
        defaultTarget: 5,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Days eating 5+ vegetable servings',
      },
      {
        id: 'water_days',
        name: 'Hydration Days',
        icon: Droplets,
        unit: 'days',
        defaultTarget: 5,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Days drinking 8+ glasses of water',
      },
      {
        id: 'fruit_days',
        name: 'Fruit Days',
        icon: Cherry,
        unit: 'days',
        defaultTarget: 5,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Days eating 2+ fruit servings',
      },
      {
        id: 'protein_days',
        name: 'Protein Goal Days',
        icon: Beef,
        unit: 'days',
        defaultTarget: 5,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Days hitting protein target',
      },
      {
        id: 'no_sugar_days',
        name: 'Low Sugar Days',
        icon: Candy,
        unit: 'days',
        defaultTarget: 4,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Days with minimal added sugar',
      },
      {
        id: 'home_cooked',
        name: 'Home Cooked Meals',
        icon: Utensils,
        unit: 'meals',
        defaultTarget: 10,
        minTarget: 3,
        maxTarget: 21,
        step: 1,
        description: 'Home-prepared meals per week',
      },
      {
        id: 'fiber_days',
        name: 'Fiber Goal Days',
        icon: Wheat,
        unit: 'days',
        defaultTarget: 5,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Days hitting 25g+ fiber',
      },
      {
        id: 'omega3_days',
        name: 'Omega-3 Days',
        icon: Fish,
        unit: 'days',
        defaultTarget: 3,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Days eating omega-3 rich foods',
      },
    ],
  },
  {
    id: 'medication',
    name: 'Medication',
    icon: Pill,
    color: 'text-orange-400',
    bgColor: 'bg-orange-500/10',
    borderColor: 'border-orange-500/30',
    goals: [
      {
        id: 'medication_doses',
        name: 'Doses Taken',
        icon: Pill,
        unit: 'doses',
        defaultTarget: 14,
        minTarget: 1,
        maxTarget: 28,
        step: 1,
        description: 'Number of medication doses taken',
      },
      {
        id: 'supplement_doses',
        name: 'Supplement Doses',
        icon: Pill,
        unit: 'doses',
        defaultTarget: 7,
        minTarget: 1,
        maxTarget: 21,
        step: 1,
        description: 'Daily supplements taken',
      },
      {
        id: 'vitamin_d',
        name: 'Vitamin D Days',
        icon: Sun,
        unit: 'days',
        defaultTarget: 7,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Days taking vitamin D',
      },
      {
        id: 'on_time_doses',
        name: 'On-Time Doses',
        icon: Clock,
        unit: 'doses',
        defaultTarget: 14,
        minTarget: 1,
        maxTarget: 28,
        step: 1,
        description: 'Doses taken within scheduled window',
      },
    ],
  },
  {
    id: 'mindfulness',
    name: 'Mindfulness',
    icon: Brain,
    color: 'text-pink-400',
    bgColor: 'bg-pink-500/10',
    borderColor: 'border-pink-500/30',
    goals: [
      {
        id: 'meditation_minutes',
        name: 'Meditation Minutes',
        icon: Brain,
        unit: 'min',
        defaultTarget: 30,
        minTarget: 5,
        maxTarget: 120,
        step: 5,
        description: 'Total minutes of meditation per week',
      },
      {
        id: 'mindful_days',
        name: 'Mindful Days',
        icon: Heart,
        unit: 'days',
        defaultTarget: 4,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Days with mindfulness practice',
      },
      {
        id: 'journaling_days',
        name: 'Journaling Days',
        icon: Book,
        unit: 'days',
        defaultTarget: 3,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Days writing in a journal',
      },
      {
        id: 'gratitude_days',
        name: 'Gratitude Practice',
        icon: Heart,
        unit: 'days',
        defaultTarget: 5,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Days practicing gratitude',
      },
      {
        id: 'breathing_sessions',
        name: 'Deep Breathing',
        icon: Wind,
        unit: 'sessions',
        defaultTarget: 5,
        minTarget: 1,
        maxTarget: 14,
        step: 1,
        description: 'Deep breathing sessions per week',
      },
      {
        id: 'digital_detox',
        name: 'Digital Detox Hours',
        icon: Smartphone,
        unit: 'hours',
        defaultTarget: 10,
        minTarget: 2,
        maxTarget: 30,
        step: 2,
        description: 'Hours away from devices per week',
      },
      {
        id: 'outdoor_time',
        name: 'Outdoor Time',
        icon: TreePine,
        unit: 'hours',
        defaultTarget: 7,
        minTarget: 1,
        maxTarget: 20,
        step: 1,
        description: 'Hours spent outdoors per week',
      },
      {
        id: 'morning_routine',
        name: 'Morning Routine Days',
        icon: Sunrise,
        unit: 'days',
        defaultTarget: 5,
        minTarget: 1,
        maxTarget: 7,
        step: 1,
        description: 'Days completing morning routine',
      },
    ],
  },
  {
    id: 'custom',
    name: 'Custom',
    icon: Sparkles,
    color: 'text-amber-400',
    bgColor: 'bg-amber-500/10',
    borderColor: 'border-amber-500/30',
    goals: [],
  },
];

export const customUnitOptions = ['days', 'times', 'min', 'hours'] as const;
export type CustomUnit = (typeof customUnitOptions)[number];
