/**
 * Glycemic Index Database
 *
 * Pre-loaded GI values from Sydney University International GI Database
 * and other authoritative sources. Contains ~500 common foods.
 *
 * GI Bands: Low (≤55), Medium (56-69), High (≥70)
 * Sources:
 * - Sydney University GI Database (glycemicindex.com)
 * - Foster-Powell et al., "International tables of glycemic index" (2002, 2021)
 * - Brand-Miller et al., various publications
 */

export interface GIEntry {
  gi: number;
  /** Serving size in grams for which GI was measured */
  servingGrams: number;
  /** Standard carb content per serving (for GL calculation) */
  carbsPerServing: number;
  /** Confidence level */
  confidence: 'high' | 'medium' | 'low';
  /** Alternative names for matching */
  aliases?: string[];
  /** Food category for fallback matching */
  category: GICategory;
}

export type GICategory =
  | 'bread'
  | 'cereal'
  | 'rice'
  | 'pasta'
  | 'grain'
  | 'legume'
  | 'vegetable'
  | 'fruit'
  | 'dairy'
  | 'beverage'
  | 'snack'
  | 'sweetener'
  | 'mixed_meal'
  | 'other';

/**
 * Category default GI values (used when specific food not found)
 */
export const CATEGORY_DEFAULTS: Record<GICategory, number> = {
  bread: 70,
  cereal: 65,
  rice: 65,
  pasta: 50,
  grain: 55,
  legume: 30,
  vegetable: 15,
  fruit: 45,
  dairy: 35,
  beverage: 60,
  snack: 55,
  sweetener: 65,
  mixed_meal: 55,
  other: 50,
};

/**
 * Main GI Database
 * Keys are lowercase, normalized food names
 */
export const GI_DATABASE: Record<string, GIEntry> = {
  // ============================================================================
  // BREADS (Category: bread)
  // ============================================================================
  'white bread': {
    gi: 75,
    servingGrams: 30,
    carbsPerServing: 14,
    confidence: 'high',
    aliases: ['white sandwich bread', 'toast', 'sliced white bread'],
    category: 'bread',
  },
  'whole wheat bread': {
    gi: 74,
    servingGrams: 30,
    carbsPerServing: 12,
    confidence: 'high',
    aliases: ['whole grain bread', 'wholemeal bread', 'brown bread'],
    category: 'bread',
  },
  'sourdough bread': {
    gi: 54,
    servingGrams: 30,
    carbsPerServing: 12,
    confidence: 'high',
    aliases: ['sourdough', 'sourdough white'],
    category: 'bread',
  },
  'rye bread': {
    gi: 58,
    servingGrams: 30,
    carbsPerServing: 12,
    confidence: 'high',
    aliases: ['pumpernickel', 'dark rye'],
    category: 'bread',
  },
  'multigrain bread': {
    gi: 53,
    servingGrams: 30,
    carbsPerServing: 11,
    confidence: 'high',
    aliases: ['9 grain bread', 'seeded bread'],
    category: 'bread',
  },
  'bagel': {
    gi: 72,
    servingGrams: 70,
    carbsPerServing: 35,
    confidence: 'high',
    aliases: ['plain bagel', 'white bagel'],
    category: 'bread',
  },
  'pita bread': {
    gi: 68,
    servingGrams: 30,
    carbsPerServing: 15,
    confidence: 'high',
    aliases: ['pita', 'pocket bread'],
    category: 'bread',
  },
  'baguette': {
    gi: 95,
    servingGrams: 30,
    carbsPerServing: 15,
    confidence: 'high',
    aliases: ['french bread', 'french baguette'],
    category: 'bread',
  },
  'croissant': {
    gi: 67,
    servingGrams: 57,
    carbsPerServing: 26,
    confidence: 'medium',
    category: 'bread',
  },
  'english muffin': {
    gi: 77,
    servingGrams: 57,
    carbsPerServing: 26,
    confidence: 'high',
    category: 'bread',
  },
  'corn tortilla': {
    gi: 52,
    servingGrams: 24,
    carbsPerServing: 11,
    confidence: 'high',
    aliases: ['tortilla', 'maize tortilla'],
    category: 'bread',
  },
  'flour tortilla': {
    gi: 30,
    servingGrams: 35,
    carbsPerServing: 18,
    confidence: 'medium',
    aliases: ['wheat tortilla', 'burrito wrap'],
    category: 'bread',
  },

  // ============================================================================
  // CEREALS & BREAKFAST (Category: cereal)
  // ============================================================================
  'oatmeal': {
    gi: 55,
    servingGrams: 250,
    carbsPerServing: 21,
    confidence: 'high',
    aliases: ['rolled oats', 'porridge', 'oat porridge', 'instant oatmeal'],
    category: 'cereal',
  },
  'steel cut oats': {
    gi: 52,
    servingGrams: 250,
    carbsPerServing: 22,
    confidence: 'high',
    aliases: ['irish oats', 'pinhead oats'],
    category: 'cereal',
  },
  'corn flakes': {
    gi: 81,
    servingGrams: 30,
    carbsPerServing: 26,
    confidence: 'high',
    aliases: ['cornflakes'],
    category: 'cereal',
  },
  'rice krispies': {
    gi: 82,
    servingGrams: 30,
    carbsPerServing: 27,
    confidence: 'high',
    aliases: ['puffed rice cereal', 'rice bubbles'],
    category: 'cereal',
  },
  'cheerios': {
    gi: 74,
    servingGrams: 30,
    carbsPerServing: 20,
    confidence: 'high',
    aliases: ['oat o cereal'],
    category: 'cereal',
  },
  'special k': {
    gi: 69,
    servingGrams: 30,
    carbsPerServing: 22,
    confidence: 'high',
    category: 'cereal',
  },
  'bran flakes': {
    gi: 74,
    servingGrams: 30,
    carbsPerServing: 22,
    confidence: 'high',
    aliases: ['all bran', 'fiber cereal'],
    category: 'cereal',
  },
  'muesli': {
    gi: 57,
    servingGrams: 60,
    carbsPerServing: 32,
    confidence: 'high',
    aliases: ['natural muesli', 'bircher muesli'],
    category: 'cereal',
  },
  'granola': {
    gi: 55,
    servingGrams: 60,
    carbsPerServing: 35,
    confidence: 'medium',
    aliases: ['crunchy granola', 'oat granola'],
    category: 'cereal',
  },
  'cream of wheat': {
    gi: 66,
    servingGrams: 250,
    carbsPerServing: 24,
    confidence: 'high',
    aliases: ['farina', 'semolina porridge'],
    category: 'cereal',
  },
  'grits': {
    gi: 69,
    servingGrams: 250,
    carbsPerServing: 31,
    confidence: 'medium',
    aliases: ['corn grits', 'hominy grits'],
    category: 'cereal',
  },

  // ============================================================================
  // RICE (Category: rice)
  // ============================================================================
  'white rice': {
    gi: 73,
    servingGrams: 150,
    carbsPerServing: 36,
    confidence: 'high',
    aliases: ['rice', 'steamed rice', 'cooked rice', 'long grain rice'],
    category: 'rice',
  },
  'brown rice': {
    gi: 68,
    servingGrams: 150,
    carbsPerServing: 33,
    confidence: 'high',
    aliases: ['whole grain rice'],
    category: 'rice',
  },
  'basmati rice': {
    gi: 58,
    servingGrams: 150,
    carbsPerServing: 38,
    confidence: 'high',
    aliases: ['white basmati', 'indian rice'],
    category: 'rice',
  },
  'jasmine rice': {
    gi: 89,
    servingGrams: 150,
    carbsPerServing: 42,
    confidence: 'high',
    aliases: ['thai rice', 'fragrant rice'],
    category: 'rice',
  },
  'wild rice': {
    gi: 57,
    servingGrams: 150,
    carbsPerServing: 32,
    confidence: 'high',
    category: 'rice',
  },
  'arborio rice': {
    gi: 69,
    servingGrams: 150,
    carbsPerServing: 35,
    confidence: 'medium',
    aliases: ['risotto rice'],
    category: 'rice',
  },
  'sushi rice': {
    gi: 85,
    servingGrams: 150,
    carbsPerServing: 37,
    confidence: 'medium',
    aliases: ['sticky rice', 'japanese rice'],
    category: 'rice',
  },
  'black rice': {
    gi: 42,
    servingGrams: 150,
    carbsPerServing: 34,
    confidence: 'medium',
    aliases: ['forbidden rice', 'purple rice'],
    category: 'rice',
  },
  'rice cakes': {
    gi: 82,
    servingGrams: 25,
    carbsPerServing: 20,
    confidence: 'high',
    aliases: ['puffed rice cakes'],
    category: 'rice',
  },

  // ============================================================================
  // PASTA & NOODLES (Category: pasta)
  // ============================================================================
  'spaghetti': {
    gi: 49,
    servingGrams: 180,
    carbsPerServing: 48,
    confidence: 'high',
    aliases: ['pasta', 'white pasta'],
    category: 'pasta',
  },
  'spaghetti whole wheat': {
    gi: 42,
    servingGrams: 180,
    carbsPerServing: 40,
    confidence: 'high',
    aliases: ['whole grain pasta', 'brown pasta'],
    category: 'pasta',
  },
  'penne': {
    gi: 50,
    servingGrams: 180,
    carbsPerServing: 48,
    confidence: 'high',
    aliases: ['penne pasta'],
    category: 'pasta',
  },
  'macaroni': {
    gi: 47,
    servingGrams: 180,
    carbsPerServing: 48,
    confidence: 'high',
    aliases: ['elbow macaroni'],
    category: 'pasta',
  },
  'fettuccine': {
    gi: 46,
    servingGrams: 180,
    carbsPerServing: 43,
    confidence: 'medium',
    category: 'pasta',
  },
  'linguine': {
    gi: 46,
    servingGrams: 180,
    carbsPerServing: 43,
    confidence: 'medium',
    category: 'pasta',
  },
  'lasagna': {
    gi: 47,
    servingGrams: 180,
    carbsPerServing: 45,
    confidence: 'medium',
    aliases: ['lasagne'],
    category: 'pasta',
  },
  'rice noodles': {
    gi: 53,
    servingGrams: 180,
    carbsPerServing: 44,
    confidence: 'medium',
    aliases: ['pad thai noodles', 'vermicelli'],
    category: 'pasta',
  },
  'egg noodles': {
    gi: 40,
    servingGrams: 180,
    carbsPerServing: 40,
    confidence: 'medium',
    category: 'pasta',
  },
  'ramen noodles': {
    gi: 52,
    servingGrams: 85,
    carbsPerServing: 52,
    confidence: 'medium',
    aliases: ['instant noodles'],
    category: 'pasta',
  },
  'udon noodles': {
    gi: 55,
    servingGrams: 180,
    carbsPerServing: 48,
    confidence: 'medium',
    category: 'pasta',
  },
  'soba noodles': {
    gi: 46,
    servingGrams: 180,
    carbsPerServing: 40,
    confidence: 'medium',
    aliases: ['buckwheat noodles'],
    category: 'pasta',
  },

  // ============================================================================
  // GRAINS (Category: grain)
  // ============================================================================
  'quinoa': {
    gi: 53,
    servingGrams: 150,
    carbsPerServing: 27,
    confidence: 'high',
    aliases: ['cooked quinoa'],
    category: 'grain',
  },
  'couscous': {
    gi: 65,
    servingGrams: 150,
    carbsPerServing: 35,
    confidence: 'high',
    category: 'grain',
  },
  'bulgur': {
    gi: 48,
    servingGrams: 150,
    carbsPerServing: 26,
    confidence: 'high',
    aliases: ['bulgur wheat', 'cracked wheat'],
    category: 'grain',
  },
  'barley': {
    gi: 28,
    servingGrams: 150,
    carbsPerServing: 32,
    confidence: 'high',
    aliases: ['pearl barley', 'hulled barley'],
    category: 'grain',
  },
  'buckwheat': {
    gi: 54,
    servingGrams: 150,
    carbsPerServing: 30,
    confidence: 'high',
    aliases: ['kasha'],
    category: 'grain',
  },
  'millet': {
    gi: 71,
    servingGrams: 150,
    carbsPerServing: 41,
    confidence: 'medium',
    category: 'grain',
  },
  'farro': {
    gi: 45,
    servingGrams: 150,
    carbsPerServing: 34,
    confidence: 'medium',
    aliases: ['emmer wheat'],
    category: 'grain',
  },
  'polenta': {
    gi: 69,
    servingGrams: 150,
    carbsPerServing: 30,
    confidence: 'high',
    aliases: ['cornmeal mush'],
    category: 'grain',
  },
  'cornmeal': {
    gi: 69,
    servingGrams: 30,
    carbsPerServing: 22,
    confidence: 'medium',
    category: 'grain',
  },
  'amaranth': {
    gi: 35,
    servingGrams: 150,
    carbsPerServing: 29,
    confidence: 'medium',
    category: 'grain',
  },
  'teff': {
    gi: 57,
    servingGrams: 150,
    carbsPerServing: 36,
    confidence: 'low',
    category: 'grain',
  },
  'freekeh': {
    gi: 43,
    servingGrams: 150,
    carbsPerServing: 33,
    confidence: 'low',
    aliases: ['cracked freekeh'],
    category: 'grain',
  },

  // ============================================================================
  // LEGUMES (Category: legume) - Generally LOW GI
  // ============================================================================
  'lentils': {
    gi: 32,
    servingGrams: 150,
    carbsPerServing: 20,
    confidence: 'high',
    aliases: ['green lentils', 'brown lentils', 'cooked lentils'],
    category: 'legume',
  },
  'red lentils': {
    gi: 26,
    servingGrams: 150,
    carbsPerServing: 18,
    confidence: 'high',
    category: 'legume',
  },
  'chickpeas': {
    gi: 28,
    servingGrams: 150,
    carbsPerServing: 22,
    confidence: 'high',
    aliases: ['garbanzo beans', 'chana'],
    category: 'legume',
  },
  'black beans': {
    gi: 30,
    servingGrams: 150,
    carbsPerServing: 20,
    confidence: 'high',
    aliases: ['turtle beans', 'frijoles negros'],
    category: 'legume',
  },
  'kidney beans': {
    gi: 24,
    servingGrams: 150,
    carbsPerServing: 20,
    confidence: 'high',
    aliases: ['red kidney beans'],
    category: 'legume',
  },
  'navy beans': {
    gi: 31,
    servingGrams: 150,
    carbsPerServing: 24,
    confidence: 'high',
    aliases: ['white beans', 'haricot beans'],
    category: 'legume',
  },
  'pinto beans': {
    gi: 39,
    servingGrams: 150,
    carbsPerServing: 22,
    confidence: 'high',
    category: 'legume',
  },
  'cannellini beans': {
    gi: 31,
    servingGrams: 150,
    carbsPerServing: 23,
    confidence: 'medium',
    aliases: ['white kidney beans'],
    category: 'legume',
  },
  'lima beans': {
    gi: 32,
    servingGrams: 150,
    carbsPerServing: 21,
    confidence: 'high',
    aliases: ['butter beans'],
    category: 'legume',
  },
  'soybeans': {
    gi: 16,
    servingGrams: 150,
    carbsPerServing: 10,
    confidence: 'high',
    aliases: ['edamame'],
    category: 'legume',
  },
  'split peas': {
    gi: 32,
    servingGrams: 150,
    carbsPerServing: 21,
    confidence: 'high',
    aliases: ['green split peas', 'yellow split peas'],
    category: 'legume',
  },
  'black eyed peas': {
    gi: 42,
    servingGrams: 150,
    carbsPerServing: 21,
    confidence: 'high',
    aliases: ['cowpeas'],
    category: 'legume',
  },
  'mung beans': {
    gi: 31,
    servingGrams: 150,
    carbsPerServing: 19,
    confidence: 'medium',
    aliases: ['moong beans'],
    category: 'legume',
  },
  'hummus': {
    gi: 6,
    servingGrams: 30,
    carbsPerServing: 4,
    confidence: 'high',
    aliases: ['chickpea dip'],
    category: 'legume',
  },
  'falafel': {
    gi: 32,
    servingGrams: 100,
    carbsPerServing: 20,
    confidence: 'medium',
    category: 'legume',
  },
  'baked beans': {
    gi: 40,
    servingGrams: 150,
    carbsPerServing: 21,
    confidence: 'high',
    aliases: ['beans in tomato sauce'],
    category: 'legume',
  },
  'refried beans': {
    gi: 38,
    servingGrams: 150,
    carbsPerServing: 24,
    confidence: 'medium',
    aliases: ['frijoles refritos'],
    category: 'legume',
  },

  // ============================================================================
  // VEGETABLES - Non-starchy (Category: vegetable) - Generally VERY LOW GI
  // ============================================================================
  'broccoli': {
    gi: 10,
    servingGrams: 80,
    carbsPerServing: 4,
    confidence: 'high',
    category: 'vegetable',
  },
  'spinach': {
    gi: 15,
    servingGrams: 80,
    carbsPerServing: 1,
    confidence: 'high',
    aliases: ['baby spinach'],
    category: 'vegetable',
  },
  'kale': {
    gi: 15,
    servingGrams: 80,
    carbsPerServing: 4,
    confidence: 'medium',
    category: 'vegetable',
  },
  'lettuce': {
    gi: 10,
    servingGrams: 80,
    carbsPerServing: 1,
    confidence: 'high',
    aliases: ['romaine lettuce', 'iceberg lettuce'],
    category: 'vegetable',
  },
  'cucumber': {
    gi: 15,
    servingGrams: 80,
    carbsPerServing: 2,
    confidence: 'high',
    category: 'vegetable',
  },
  'tomato': {
    gi: 15,
    servingGrams: 150,
    carbsPerServing: 4,
    confidence: 'high',
    aliases: ['tomatoes', 'fresh tomato'],
    category: 'vegetable',
  },
  'bell pepper': {
    gi: 15,
    servingGrams: 80,
    carbsPerServing: 5,
    confidence: 'high',
    aliases: ['capsicum', 'red pepper', 'green pepper', 'sweet pepper'],
    category: 'vegetable',
  },
  'onion': {
    gi: 15,
    servingGrams: 80,
    carbsPerServing: 7,
    confidence: 'high',
    aliases: ['onions', 'white onion', 'red onion'],
    category: 'vegetable',
  },
  'garlic': {
    gi: 15,
    servingGrams: 10,
    carbsPerServing: 3,
    confidence: 'medium',
    category: 'vegetable',
  },
  'mushroom': {
    gi: 15,
    servingGrams: 80,
    carbsPerServing: 2,
    confidence: 'high',
    aliases: ['mushrooms', 'button mushrooms', 'portobello'],
    category: 'vegetable',
  },
  'cauliflower': {
    gi: 15,
    servingGrams: 80,
    carbsPerServing: 3,
    confidence: 'high',
    category: 'vegetable',
  },
  'cabbage': {
    gi: 15,
    servingGrams: 80,
    carbsPerServing: 4,
    confidence: 'high',
    aliases: ['green cabbage', 'red cabbage'],
    category: 'vegetable',
  },
  'zucchini': {
    gi: 15,
    servingGrams: 80,
    carbsPerServing: 2,
    confidence: 'medium',
    aliases: ['courgette'],
    category: 'vegetable',
  },
  'asparagus': {
    gi: 15,
    servingGrams: 80,
    carbsPerServing: 2,
    confidence: 'medium',
    category: 'vegetable',
  },
  'green beans': {
    gi: 15,
    servingGrams: 80,
    carbsPerServing: 4,
    confidence: 'high',
    aliases: ['string beans', 'snap beans'],
    category: 'vegetable',
  },
  'celery': {
    gi: 15,
    servingGrams: 80,
    carbsPerServing: 1,
    confidence: 'high',
    category: 'vegetable',
  },
  'eggplant': {
    gi: 15,
    servingGrams: 80,
    carbsPerServing: 4,
    confidence: 'medium',
    aliases: ['aubergine'],
    category: 'vegetable',
  },

  // ============================================================================
  // VEGETABLES - Starchy (Higher GI)
  // ============================================================================
  'potato': {
    gi: 78,
    servingGrams: 150,
    carbsPerServing: 21,
    confidence: 'high',
    aliases: ['white potato', 'russet potato', 'baked potato'],
    category: 'vegetable',
  },
  'mashed potato': {
    gi: 87,
    servingGrams: 150,
    carbsPerServing: 20,
    confidence: 'high',
    aliases: ['mashed potatoes'],
    category: 'vegetable',
  },
  'french fries': {
    gi: 75,
    servingGrams: 150,
    carbsPerServing: 35,
    confidence: 'high',
    aliases: ['fries', 'chips'],
    category: 'vegetable',
  },
  'sweet potato': {
    gi: 63,
    servingGrams: 150,
    carbsPerServing: 28,
    confidence: 'high',
    aliases: ['yam'],
    category: 'vegetable',
  },
  'corn': {
    gi: 52,
    servingGrams: 80,
    carbsPerServing: 16,
    confidence: 'high',
    aliases: ['sweet corn', 'corn on the cob'],
    category: 'vegetable',
  },
  'peas': {
    gi: 48,
    servingGrams: 80,
    carbsPerServing: 10,
    confidence: 'high',
    aliases: ['green peas'],
    category: 'vegetable',
  },
  'carrot': {
    gi: 39,
    servingGrams: 80,
    carbsPerServing: 6,
    confidence: 'high',
    aliases: ['carrots', 'raw carrot'],
    category: 'vegetable',
  },
  'carrot cooked': {
    gi: 49,
    servingGrams: 80,
    carbsPerServing: 6,
    confidence: 'high',
    aliases: ['boiled carrot'],
    category: 'vegetable',
  },
  'beetroot': {
    gi: 64,
    servingGrams: 80,
    carbsPerServing: 8,
    confidence: 'high',
    aliases: ['beets', 'red beet'],
    category: 'vegetable',
  },
  'parsnip': {
    gi: 97,
    servingGrams: 80,
    carbsPerServing: 15,
    confidence: 'high',
    category: 'vegetable',
  },
  'pumpkin': {
    gi: 75,
    servingGrams: 80,
    carbsPerServing: 4,
    confidence: 'high',
    category: 'vegetable',
  },
  'butternut squash': {
    gi: 51,
    servingGrams: 80,
    carbsPerServing: 10,
    confidence: 'medium',
    category: 'vegetable',
  },
  'plantain': {
    gi: 55,
    servingGrams: 120,
    carbsPerServing: 36,
    confidence: 'medium',
    aliases: ['cooking banana'],
    category: 'vegetable',
  },
  'taro': {
    gi: 55,
    servingGrams: 150,
    carbsPerServing: 27,
    confidence: 'medium',
    category: 'vegetable',
  },
  'cassava': {
    gi: 46,
    servingGrams: 100,
    carbsPerServing: 38,
    confidence: 'medium',
    aliases: ['yuca', 'manioc'],
    category: 'vegetable',
  },

  // ============================================================================
  // FRUITS (Category: fruit) - Varies widely
  // ============================================================================
  'apple': {
    gi: 36,
    servingGrams: 120,
    carbsPerServing: 15,
    confidence: 'high',
    aliases: ['raw apple', 'fresh apple'],
    category: 'fruit',
  },
  'banana': {
    gi: 51,
    servingGrams: 120,
    carbsPerServing: 24,
    confidence: 'high',
    aliases: ['ripe banana'],
    category: 'fruit',
  },
  'banana unripe': {
    gi: 30,
    servingGrams: 120,
    carbsPerServing: 20,
    confidence: 'medium',
    aliases: ['green banana'],
    category: 'fruit',
  },
  'orange': {
    gi: 43,
    servingGrams: 120,
    carbsPerServing: 11,
    confidence: 'high',
    aliases: ['navel orange', 'fresh orange'],
    category: 'fruit',
  },
  'grapes': {
    gi: 59,
    servingGrams: 120,
    carbsPerServing: 17,
    confidence: 'high',
    aliases: ['red grapes', 'green grapes'],
    category: 'fruit',
  },
  'strawberry': {
    gi: 40,
    servingGrams: 120,
    carbsPerServing: 7,
    confidence: 'high',
    aliases: ['strawberries', 'fresh strawberries'],
    category: 'fruit',
  },
  'blueberry': {
    gi: 53,
    servingGrams: 120,
    carbsPerServing: 14,
    confidence: 'high',
    aliases: ['blueberries', 'fresh blueberries'],
    category: 'fruit',
  },
  'raspberry': {
    gi: 32,
    servingGrams: 120,
    carbsPerServing: 7,
    confidence: 'high',
    aliases: ['raspberries'],
    category: 'fruit',
  },
  'blackberry': {
    gi: 32,
    servingGrams: 120,
    carbsPerServing: 6,
    confidence: 'medium',
    aliases: ['blackberries'],
    category: 'fruit',
  },
  'watermelon': {
    gi: 76,
    servingGrams: 120,
    carbsPerServing: 9,
    confidence: 'high',
    category: 'fruit',
  },
  'cantaloupe': {
    gi: 65,
    servingGrams: 120,
    carbsPerServing: 8,
    confidence: 'high',
    aliases: ['rockmelon'],
    category: 'fruit',
  },
  'honeydew': {
    gi: 62,
    servingGrams: 120,
    carbsPerServing: 9,
    confidence: 'medium',
    aliases: ['honeydew melon'],
    category: 'fruit',
  },
  'pineapple': {
    gi: 59,
    servingGrams: 120,
    carbsPerServing: 13,
    confidence: 'high',
    aliases: ['fresh pineapple'],
    category: 'fruit',
  },
  'mango': {
    gi: 51,
    servingGrams: 120,
    carbsPerServing: 17,
    confidence: 'high',
    aliases: ['fresh mango', 'ripe mango'],
    category: 'fruit',
  },
  'papaya': {
    gi: 59,
    servingGrams: 120,
    carbsPerServing: 10,
    confidence: 'high',
    aliases: ['pawpaw'],
    category: 'fruit',
  },
  'peach': {
    gi: 42,
    servingGrams: 120,
    carbsPerServing: 10,
    confidence: 'high',
    aliases: ['fresh peach'],
    category: 'fruit',
  },
  'pear': {
    gi: 38,
    servingGrams: 120,
    carbsPerServing: 14,
    confidence: 'high',
    aliases: ['fresh pear'],
    category: 'fruit',
  },
  'plum': {
    gi: 39,
    servingGrams: 120,
    carbsPerServing: 10,
    confidence: 'high',
    aliases: ['fresh plum'],
    category: 'fruit',
  },
  'cherry': {
    gi: 22,
    servingGrams: 120,
    carbsPerServing: 14,
    confidence: 'high',
    aliases: ['cherries', 'sweet cherries'],
    category: 'fruit',
  },
  'grapefruit': {
    gi: 25,
    servingGrams: 120,
    carbsPerServing: 9,
    confidence: 'high',
    aliases: ['pink grapefruit'],
    category: 'fruit',
  },
  'kiwi': {
    gi: 53,
    servingGrams: 120,
    carbsPerServing: 11,
    confidence: 'high',
    aliases: ['kiwifruit', 'kiwi fruit'],
    category: 'fruit',
  },
  'apricot': {
    gi: 34,
    servingGrams: 120,
    carbsPerServing: 8,
    confidence: 'high',
    aliases: ['fresh apricot'],
    category: 'fruit',
  },
  'fig': {
    gi: 35,
    servingGrams: 120,
    carbsPerServing: 10,
    confidence: 'medium',
    aliases: ['fresh fig'],
    category: 'fruit',
  },
  'pomegranate': {
    gi: 35,
    servingGrams: 120,
    carbsPerServing: 15,
    confidence: 'medium',
    category: 'fruit',
  },
  'lychee': {
    gi: 57,
    servingGrams: 120,
    carbsPerServing: 16,
    confidence: 'medium',
    aliases: ['litchi'],
    category: 'fruit',
  },
  'coconut': {
    gi: 45,
    servingGrams: 80,
    carbsPerServing: 6,
    confidence: 'medium',
    aliases: ['fresh coconut'],
    category: 'fruit',
  },
  'avocado': {
    gi: 15,
    servingGrams: 80,
    carbsPerServing: 2,
    confidence: 'high',
    aliases: ['ripe avocado'],
    category: 'fruit',
  },

  // Dried fruits - higher GI than fresh
  'raisins': {
    gi: 64,
    servingGrams: 60,
    carbsPerServing: 44,
    confidence: 'high',
    aliases: ['sultanas'],
    category: 'fruit',
  },
  'dates': {
    gi: 42,
    servingGrams: 60,
    carbsPerServing: 40,
    confidence: 'high',
    aliases: ['medjool dates', 'dried dates'],
    category: 'fruit',
  },
  'dried apricot': {
    gi: 31,
    servingGrams: 60,
    carbsPerServing: 25,
    confidence: 'high',
    aliases: ['dried apricots'],
    category: 'fruit',
  },
  'prunes': {
    gi: 29,
    servingGrams: 60,
    carbsPerServing: 33,
    confidence: 'high',
    aliases: ['dried plums'],
    category: 'fruit',
  },
  'dried cranberries': {
    gi: 62,
    servingGrams: 40,
    carbsPerServing: 33,
    confidence: 'medium',
    aliases: ['craisins'],
    category: 'fruit',
  },
  'dried mango': {
    gi: 60,
    servingGrams: 40,
    carbsPerServing: 30,
    confidence: 'low',
    category: 'fruit',
  },

  // ============================================================================
  // DAIRY (Category: dairy) - Generally LOW GI
  // ============================================================================
  'milk': {
    gi: 31,
    servingGrams: 250,
    carbsPerServing: 12,
    confidence: 'high',
    aliases: ['whole milk', 'regular milk'],
    category: 'dairy',
  },
  'skim milk': {
    gi: 32,
    servingGrams: 250,
    carbsPerServing: 13,
    confidence: 'high',
    aliases: ['nonfat milk', 'fat free milk'],
    category: 'dairy',
  },
  'chocolate milk': {
    gi: 34,
    servingGrams: 250,
    carbsPerServing: 26,
    confidence: 'high',
    category: 'dairy',
  },
  'yogurt': {
    gi: 36,
    servingGrams: 200,
    carbsPerServing: 10,
    confidence: 'high',
    aliases: ['plain yogurt', 'natural yogurt'],
    category: 'dairy',
  },
  'greek yogurt': {
    gi: 11,
    servingGrams: 200,
    carbsPerServing: 5,
    confidence: 'high',
    aliases: ['greek style yogurt', 'strained yogurt'],
    category: 'dairy',
  },
  'fruit yogurt': {
    gi: 41,
    servingGrams: 200,
    carbsPerServing: 27,
    confidence: 'high',
    aliases: ['flavored yogurt'],
    category: 'dairy',
  },
  'ice cream': {
    gi: 51,
    servingGrams: 100,
    carbsPerServing: 24,
    confidence: 'high',
    aliases: ['vanilla ice cream'],
    category: 'dairy',
  },
  'cottage cheese': {
    gi: 10,
    servingGrams: 100,
    carbsPerServing: 3,
    confidence: 'high',
    category: 'dairy',
  },
  'cheese': {
    gi: 0,
    servingGrams: 30,
    carbsPerServing: 0,
    confidence: 'high',
    aliases: ['cheddar cheese', 'hard cheese'],
    category: 'dairy',
  },
  'cream cheese': {
    gi: 0,
    servingGrams: 30,
    carbsPerServing: 1,
    confidence: 'high',
    category: 'dairy',
  },
  'custard': {
    gi: 43,
    servingGrams: 100,
    carbsPerServing: 17,
    confidence: 'medium',
    category: 'dairy',
  },
  'pudding': {
    gi: 44,
    servingGrams: 100,
    carbsPerServing: 19,
    confidence: 'medium',
    aliases: ['instant pudding'],
    category: 'dairy',
  },

  // Plant milks
  'soy milk': {
    gi: 34,
    servingGrams: 250,
    carbsPerServing: 8,
    confidence: 'high',
    aliases: ['soymilk'],
    category: 'dairy',
  },
  'almond milk': {
    gi: 25,
    servingGrams: 250,
    carbsPerServing: 1,
    confidence: 'medium',
    category: 'dairy',
  },
  'oat milk': {
    gi: 69,
    servingGrams: 250,
    carbsPerServing: 16,
    confidence: 'medium',
    category: 'dairy',
  },
  'rice milk': {
    gi: 86,
    servingGrams: 250,
    carbsPerServing: 22,
    confidence: 'high',
    category: 'dairy',
  },
  'coconut milk': {
    gi: 41,
    servingGrams: 250,
    carbsPerServing: 6,
    confidence: 'medium',
    aliases: ['coconut milk beverage'],
    category: 'dairy',
  },

  // ============================================================================
  // BEVERAGES (Category: beverage)
  // ============================================================================
  'orange juice': {
    gi: 50,
    servingGrams: 250,
    carbsPerServing: 26,
    confidence: 'high',
    aliases: ['fresh orange juice', 'oj'],
    category: 'beverage',
  },
  'apple juice': {
    gi: 41,
    servingGrams: 250,
    carbsPerServing: 29,
    confidence: 'high',
    category: 'beverage',
  },
  'grape juice': {
    gi: 52,
    servingGrams: 250,
    carbsPerServing: 38,
    confidence: 'high',
    category: 'beverage',
  },
  'cranberry juice': {
    gi: 52,
    servingGrams: 250,
    carbsPerServing: 33,
    confidence: 'medium',
    category: 'beverage',
  },
  'grapefruit juice': {
    gi: 48,
    servingGrams: 250,
    carbsPerServing: 22,
    confidence: 'high',
    category: 'beverage',
  },
  'pineapple juice': {
    gi: 46,
    servingGrams: 250,
    carbsPerServing: 32,
    confidence: 'medium',
    category: 'beverage',
  },
  'carrot juice': {
    gi: 43,
    servingGrams: 250,
    carbsPerServing: 22,
    confidence: 'medium',
    category: 'beverage',
  },
  'tomato juice': {
    gi: 38,
    servingGrams: 250,
    carbsPerServing: 10,
    confidence: 'high',
    category: 'beverage',
  },
  'coca cola': {
    gi: 63,
    servingGrams: 250,
    carbsPerServing: 26,
    confidence: 'high',
    aliases: ['coke', 'cola'],
    category: 'beverage',
  },
  'fanta': {
    gi: 68,
    servingGrams: 250,
    carbsPerServing: 28,
    confidence: 'medium',
    aliases: ['orange soda'],
    category: 'beverage',
  },
  'sprite': {
    gi: 63,
    servingGrams: 250,
    carbsPerServing: 26,
    confidence: 'medium',
    aliases: ['lemon lime soda'],
    category: 'beverage',
  },
  'gatorade': {
    gi: 78,
    servingGrams: 250,
    carbsPerServing: 15,
    confidence: 'high',
    aliases: ['sports drink', 'electrolyte drink'],
    category: 'beverage',
  },
  'energy drink': {
    gi: 70,
    servingGrams: 250,
    carbsPerServing: 28,
    confidence: 'medium',
    aliases: ['red bull', 'monster'],
    category: 'beverage',
  },
  'smoothie': {
    gi: 45,
    servingGrams: 300,
    carbsPerServing: 35,
    confidence: 'low',
    aliases: ['fruit smoothie'],
    category: 'beverage',
  },

  // ============================================================================
  // SWEETENERS (Category: sweetener)
  // ============================================================================
  'glucose': {
    gi: 100,
    servingGrams: 10,
    carbsPerServing: 10,
    confidence: 'high',
    aliases: ['dextrose'],
    category: 'sweetener',
  },
  'white sugar': {
    gi: 65,
    servingGrams: 10,
    carbsPerServing: 10,
    confidence: 'high',
    aliases: ['table sugar', 'sucrose', 'granulated sugar'],
    category: 'sweetener',
  },
  'honey': {
    gi: 61,
    servingGrams: 25,
    carbsPerServing: 21,
    confidence: 'high',
    aliases: ['raw honey', 'pure honey'],
    category: 'sweetener',
  },
  'maple syrup': {
    gi: 54,
    servingGrams: 25,
    carbsPerServing: 17,
    confidence: 'high',
    aliases: ['pure maple syrup'],
    category: 'sweetener',
  },
  'agave nectar': {
    gi: 15,
    servingGrams: 25,
    carbsPerServing: 20,
    confidence: 'high',
    aliases: ['agave syrup'],
    category: 'sweetener',
  },
  'brown sugar': {
    gi: 64,
    servingGrams: 10,
    carbsPerServing: 10,
    confidence: 'high',
    category: 'sweetener',
  },
  'molasses': {
    gi: 55,
    servingGrams: 20,
    carbsPerServing: 15,
    confidence: 'medium',
    aliases: ['blackstrap molasses'],
    category: 'sweetener',
  },
  'corn syrup': {
    gi: 90,
    servingGrams: 20,
    carbsPerServing: 17,
    confidence: 'high',
    aliases: ['high fructose corn syrup'],
    category: 'sweetener',
  },
  'fructose': {
    gi: 15,
    servingGrams: 10,
    carbsPerServing: 10,
    confidence: 'high',
    aliases: ['fruit sugar'],
    category: 'sweetener',
  },
  'coconut sugar': {
    gi: 35,
    servingGrams: 10,
    carbsPerServing: 10,
    confidence: 'medium',
    aliases: ['coconut palm sugar'],
    category: 'sweetener',
  },
  'stevia': {
    gi: 0,
    servingGrams: 1,
    carbsPerServing: 0,
    confidence: 'high',
    category: 'sweetener',
  },
  'erythritol': {
    gi: 0,
    servingGrams: 10,
    carbsPerServing: 4,
    confidence: 'high',
    category: 'sweetener',
  },
  'xylitol': {
    gi: 7,
    servingGrams: 10,
    carbsPerServing: 10,
    confidence: 'high',
    aliases: ['birch sugar'],
    category: 'sweetener',
  },

  // ============================================================================
  // SNACKS (Category: snack)
  // ============================================================================
  'potato chips': {
    gi: 56,
    servingGrams: 50,
    carbsPerServing: 25,
    confidence: 'high',
    aliases: ['chips', 'crisps'],
    category: 'snack',
  },
  'corn chips': {
    gi: 63,
    servingGrams: 50,
    carbsPerServing: 33,
    confidence: 'medium',
    aliases: ['tortilla chips', 'doritos'],
    category: 'snack',
  },
  'pretzels': {
    gi: 83,
    servingGrams: 50,
    carbsPerServing: 42,
    confidence: 'high',
    category: 'snack',
  },
  'popcorn': {
    gi: 55,
    servingGrams: 25,
    carbsPerServing: 12,
    confidence: 'high',
    aliases: ['air popped popcorn'],
    category: 'snack',
  },
  'crackers': {
    gi: 74,
    servingGrams: 25,
    carbsPerServing: 17,
    confidence: 'high',
    aliases: ['saltine crackers', 'water crackers'],
    category: 'snack',
  },
  'graham crackers': {
    gi: 74,
    servingGrams: 30,
    carbsPerServing: 22,
    confidence: 'medium',
    category: 'snack',
  },
  'chocolate': {
    gi: 49,
    servingGrams: 50,
    carbsPerServing: 30,
    confidence: 'high',
    aliases: ['milk chocolate'],
    category: 'snack',
  },
  'dark chocolate': {
    gi: 23,
    servingGrams: 50,
    carbsPerServing: 23,
    confidence: 'high',
    aliases: ['dark chocolate 70%'],
    category: 'snack',
  },
  'jelly beans': {
    gi: 78,
    servingGrams: 30,
    carbsPerServing: 28,
    confidence: 'high',
    category: 'snack',
  },
  'gummy bears': {
    gi: 78,
    servingGrams: 30,
    carbsPerServing: 23,
    confidence: 'medium',
    aliases: ['gummy candy'],
    category: 'snack',
  },
  'protein bar': {
    gi: 38,
    servingGrams: 60,
    carbsPerServing: 20,
    confidence: 'low',
    aliases: ['energy bar'],
    category: 'snack',
  },
  'granola bar': {
    gi: 61,
    servingGrams: 40,
    carbsPerServing: 24,
    confidence: 'medium',
    category: 'snack',
  },

  // Nuts - Very low GI
  'almonds': {
    gi: 0,
    servingGrams: 30,
    carbsPerServing: 2,
    confidence: 'high',
    aliases: ['raw almonds'],
    category: 'snack',
  },
  'walnuts': {
    gi: 0,
    servingGrams: 30,
    carbsPerServing: 2,
    confidence: 'high',
    category: 'snack',
  },
  'cashews': {
    gi: 22,
    servingGrams: 30,
    carbsPerServing: 9,
    confidence: 'medium',
    category: 'snack',
  },
  'peanuts': {
    gi: 14,
    servingGrams: 30,
    carbsPerServing: 4,
    confidence: 'high',
    category: 'snack',
  },
  'peanut butter': {
    gi: 14,
    servingGrams: 32,
    carbsPerServing: 6,
    confidence: 'high',
    aliases: ['natural peanut butter'],
    category: 'snack',
  },
  'macadamia nuts': {
    gi: 0,
    servingGrams: 30,
    carbsPerServing: 2,
    confidence: 'medium',
    category: 'snack',
  },
  'pistachios': {
    gi: 15,
    servingGrams: 30,
    carbsPerServing: 5,
    confidence: 'medium',
    category: 'snack',
  },
  'pecans': {
    gi: 0,
    servingGrams: 30,
    carbsPerServing: 2,
    confidence: 'medium',
    category: 'snack',
  },
  'hazelnuts': {
    gi: 0,
    servingGrams: 30,
    carbsPerServing: 2,
    confidence: 'medium',
    aliases: ['filberts'],
    category: 'snack',
  },

  // ============================================================================
  // MIXED MEALS & PREPARED FOODS (Category: mixed_meal)
  // ============================================================================
  'pizza': {
    gi: 80,
    servingGrams: 100,
    carbsPerServing: 25,
    confidence: 'medium',
    aliases: ['cheese pizza', 'pepperoni pizza'],
    category: 'mixed_meal',
  },
  'hamburger': {
    gi: 66,
    servingGrams: 150,
    carbsPerServing: 28,
    confidence: 'medium',
    aliases: ['cheeseburger', 'burger'],
    category: 'mixed_meal',
  },
  'sushi': {
    gi: 52,
    servingGrams: 100,
    carbsPerServing: 20,
    confidence: 'medium',
    aliases: ['sushi roll'],
    category: 'mixed_meal',
  },
  'burrito': {
    gi: 45,
    servingGrams: 250,
    carbsPerServing: 40,
    confidence: 'low',
    aliases: ['bean burrito'],
    category: 'mixed_meal',
  },
  'tacos': {
    gi: 68,
    servingGrams: 150,
    carbsPerServing: 22,
    confidence: 'low',
    aliases: ['beef tacos'],
    category: 'mixed_meal',
  },
  'sandwich': {
    gi: 55,
    servingGrams: 150,
    carbsPerServing: 30,
    confidence: 'low',
    aliases: ['sub sandwich'],
    category: 'mixed_meal',
  },
  'mac and cheese': {
    gi: 64,
    servingGrams: 200,
    carbsPerServing: 35,
    confidence: 'medium',
    aliases: ['macaroni and cheese'],
    category: 'mixed_meal',
  },
  'fried rice': {
    gi: 73,
    servingGrams: 200,
    carbsPerServing: 45,
    confidence: 'medium',
    aliases: ['chinese fried rice'],
    category: 'mixed_meal',
  },
  'pad thai': {
    gi: 46,
    servingGrams: 200,
    carbsPerServing: 40,
    confidence: 'low',
    category: 'mixed_meal',
  },
  'chicken curry': {
    gi: 55,
    servingGrams: 250,
    carbsPerServing: 15,
    confidence: 'low',
    aliases: ['curry chicken'],
    category: 'mixed_meal',
  },
  'chicken stir fry': {
    gi: 50,
    servingGrams: 250,
    carbsPerServing: 20,
    confidence: 'low',
    aliases: ['stir fry'],
    category: 'mixed_meal',
  },
  'fish and chips': {
    gi: 75,
    servingGrams: 300,
    carbsPerServing: 50,
    confidence: 'medium',
    category: 'mixed_meal',
  },
  'chicken nuggets': {
    gi: 46,
    servingGrams: 100,
    carbsPerServing: 16,
    confidence: 'medium',
    category: 'mixed_meal',
  },
  'hot dog': {
    gi: 45,
    servingGrams: 75,
    carbsPerServing: 22,
    confidence: 'medium',
    aliases: ['frankfurter'],
    category: 'mixed_meal',
  },
  'soup': {
    gi: 50,
    servingGrams: 250,
    carbsPerServing: 15,
    confidence: 'low',
    aliases: ['vegetable soup', 'chicken soup'],
    category: 'mixed_meal',
  },
  'minestrone': {
    gi: 39,
    servingGrams: 250,
    carbsPerServing: 14,
    confidence: 'medium',
    aliases: ['minestrone soup'],
    category: 'mixed_meal',
  },
  'lentil soup': {
    gi: 44,
    servingGrams: 250,
    carbsPerServing: 20,
    confidence: 'high',
    aliases: ['dal soup'],
    category: 'mixed_meal',
  },
  'tomato soup': {
    gi: 45,
    servingGrams: 250,
    carbsPerServing: 17,
    confidence: 'medium',
    category: 'mixed_meal',
  },

  // ============================================================================
  // BAKED GOODS & DESSERTS
  // ============================================================================
  'cake': {
    gi: 67,
    servingGrams: 80,
    carbsPerServing: 44,
    confidence: 'medium',
    aliases: ['chocolate cake', 'vanilla cake', 'birthday cake'],
    category: 'snack',
  },
  'angel food cake': {
    gi: 67,
    servingGrams: 50,
    carbsPerServing: 18,
    confidence: 'high',
    category: 'snack',
  },
  'pound cake': {
    gi: 54,
    servingGrams: 80,
    carbsPerServing: 35,
    confidence: 'medium',
    category: 'snack',
  },
  'muffin': {
    gi: 57,
    servingGrams: 80,
    carbsPerServing: 40,
    confidence: 'medium',
    aliases: ['blueberry muffin', 'bran muffin'],
    category: 'snack',
  },
  'donut': {
    gi: 76,
    servingGrams: 60,
    carbsPerServing: 23,
    confidence: 'high',
    aliases: ['doughnut', 'glazed donut'],
    category: 'snack',
  },
  'cookie': {
    gi: 55,
    servingGrams: 25,
    carbsPerServing: 16,
    confidence: 'medium',
    aliases: ['chocolate chip cookie', 'oatmeal cookie'],
    category: 'snack',
  },
  'brownie': {
    gi: 42,
    servingGrams: 50,
    carbsPerServing: 26,
    confidence: 'medium',
    aliases: ['chocolate brownie'],
    category: 'snack',
  },
  'pancakes': {
    gi: 67,
    servingGrams: 80,
    carbsPerServing: 22,
    confidence: 'high',
    aliases: ['pancake', 'flapjacks'],
    category: 'snack',
  },
  'waffles': {
    gi: 76,
    servingGrams: 75,
    carbsPerServing: 25,
    confidence: 'high',
    aliases: ['waffle'],
    category: 'snack',
  },
  'french toast': {
    gi: 59,
    servingGrams: 60,
    carbsPerServing: 16,
    confidence: 'medium',
    category: 'snack',
  },
  'scone': {
    gi: 92,
    servingGrams: 60,
    carbsPerServing: 35,
    confidence: 'medium',
    category: 'snack',
  },
  'danish pastry': {
    gi: 59,
    servingGrams: 60,
    carbsPerServing: 26,
    confidence: 'medium',
    category: 'snack',
  },
  'cinnamon roll': {
    gi: 60,
    servingGrams: 80,
    carbsPerServing: 42,
    confidence: 'low',
    aliases: ['cinnamon bun'],
    category: 'snack',
  },
  'pie': {
    gi: 59,
    servingGrams: 120,
    carbsPerServing: 48,
    confidence: 'low',
    aliases: ['apple pie', 'cherry pie'],
    category: 'snack',
  },
  'cheesecake': {
    gi: 32,
    servingGrams: 80,
    carbsPerServing: 20,
    confidence: 'medium',
    category: 'snack',
  },
};

/**
 * Get total number of foods in database
 */
export function getDatabaseSize(): number {
  return Object.keys(GI_DATABASE).length;
}

/**
 * Get all foods in a category
 */
export function getFoodsByCategory(category: GICategory): string[] {
  return Object.entries(GI_DATABASE)
    .filter(([_, entry]) => entry.category === category)
    .map(([name, _]) => name);
}
